language: android

services:
  - docker

script:
  - docker run -it circleci/android:api-25-node bash -c "cd ~ && git clone https://github.com/srikanth-lingala/zip4j-android-test.git && cd zip4j-android-test && ./test_zip4j.sh"